// =======================================================
var idCrop = charIDToTypeID( "Crop" );
    var desc1568 = new ActionDescriptor();
    var idT = charIDToTypeID( "T   " );
        var desc1569 = new ActionDescriptor();
        var idTop = charIDToTypeID( "Top " );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc1569.putUnitDouble( idTop, idPxl, 0.000000 );
        var idLeft = charIDToTypeID( "Left" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc1569.putUnitDouble( idLeft, idPxl, -7560.000000 );
        var idBtom = charIDToTypeID( "Btom" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc1569.putUnitDouble( idBtom, idPxl, 1350.000000 );
        var idRght = charIDToTypeID( "Rght" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc1569.putUnitDouble( idRght, idPxl, 1080.000000 );
    var idRctn = charIDToTypeID( "Rctn" );
    desc1568.putObject( idT, idRctn, desc1569 );
    var idAngl = charIDToTypeID( "Angl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc1568.putUnitDouble( idAngl, idAng, 0.000000 );
    var idDlt = charIDToTypeID( "Dlt " );
    desc1568.putBoolean( idDlt, false );
    var idAutoFillMethod = stringIDToTypeID( "AutoFillMethod" );
    desc1568.putInteger( idAutoFillMethod, 1 );
    var idcropAspectRatioModeKey = stringIDToTypeID( "cropAspectRatioModeKey" );
    var idcropAspectRatioModeClass = stringIDToTypeID( "cropAspectRatioModeClass" );
    var idpureAspectRatio = stringIDToTypeID( "pureAspectRatio" );
    desc1568.putEnumerated( idcropAspectRatioModeKey, idcropAspectRatioModeClass, idpureAspectRatio );
    var idCnsP = charIDToTypeID( "CnsP" );
    desc1568.putBoolean( idCnsP, false );
executeAction( idCrop, desc1568, DialogModes.NO );